# Generated by Django 2.2.5 on 2019-09-28 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=225)),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=225)),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=225)),
                ('numero', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('objectif', tinymce.models.HTMLField(verbose_name='Objectif')),
                ('prix', models.CharField(max_length=255)),
                ('elgibilite', tinymce.models.HTMLField(verbose_name='Eligibilite')),
                ('nombre_place', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('programme_debut', models.TimeField()),
                ('programme_fin', models.TimeField()),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cours', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='them_cour', to='education_app.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='chapitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenue', tinymce.models.HTMLField(verbose_name='contenue')),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('cour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour_chap', to='education_app.Cours')),
            ],
        ),
    ]
